services:
  uniportical:
    image: opop4444/uniportical:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    command: ["poll"]
